services:
  - type: web
    name: githubwrapped-backend
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py -k uvicorn.workers.UvicornWorker app:app
